backend/urls.py
from django.conf import settings
from django.conf.urls.static import static, serve
from django.contrib import admin
from django.urls import path, include
from .views import about_page

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('projects/', include('projects.urls')),
    path('about/', about_page),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.page, name='all_articles'),
    path('<slug>/', views.detail, name='article'),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.page),
]

projects/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'projects'

urlpatterns = [
    path('<slug>/', views.detail, name='detail'),
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(models.Model):
    slug = models.SlugField(max_length=80)
    title = models.CharField(max_length=120)
    subtitle = models.CharField(max_length=120, blank=True)
    date = models.DateField(auto_now_add=True)
    description = models.TextField()
    image = models.ImageField(blank=True)
    show = models.BooleanField()
    lock = models.BooleanField()
    love_reacts = models.IntegerField(default=0)
    categories = models.ManyToManyField('Category', related_name='posts')

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.title

    @property
    def get_all_categories(self):
        category_qs = self.categories.all()
        if category_qs.exists():
            return category_qs
        return None


class Comment(models.Model):
    name = models.CharField(max_length=80)
    comment = models.TextField()
    date = models.DateField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

home/models.py
from django.db import models


class Link(models.Model):
    link = models.URLField()
    show = models.BooleanField()
    alt_text = models.CharField(max_length=15, blank=True)
    img_class = models.CharField(max_length=40)

    def __str__(self):
        return self.alt_text

projects/models.py
from django.db import models


class Tech(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Project(models.Model):
    slug = models.SlugField(max_length=80)
    title = models.CharField(max_length=120)
    subtitle = models.CharField(max_length=120, blank=True)
    description = models.TextField(blank=True)
    image = models.ImageField()
    show = models.BooleanField()
    lock = models.BooleanField()
    tech = models.ManyToManyField('Tech', related_name='techs')

    def __str__(self):
        return self.title

    @property
    def get_all_tech(self):
        tech_qs = self.tech.all()
        if tech_qs.exists():
            return tech_qs
        return None

    class Meta:
        ordering = ['-pk']

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Name"})
    )
    comment = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
    )

backend/views.py
from home.models import Link
from django.shortcuts import render


def about_page(request):
    social_links = Link.objects.all()
    context = {'social_links': social_links}
    return render(request, 'home/about.html', context)

blog/views.py
from django.shortcuts import render
from blog.models import Post, Comment
from home.models import Link
from django.http import HttpResponse
from blog.forms import CommentForm
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger


def page(request):
    social_links = Link.objects.all()
    blog_posts = Post.objects.all()
    paginator = Paginator(blog_posts, 24)
    page = request.GET.get('page')

    try:
        blog_posts = paginator.page(page)
    except PageNotAnInteger:
        blog_posts = paginator.page(1)
    except EmptyPage:
        blog_posts = paginator.page(paginator.num_pages)

    context = {'social_links': social_links, 'blog_posts': blog_posts}
    return render(request, 'blog/base.html', context)


def detail(request, slug):
    post_query_set = Post.objects.filter(slug=slug)
    if post_query_set.exists():
        post = post_query_set.first()
    else:
        return HttpResponse(status=404)
    comments = Comment.objects.filter(post=post)
    social_links = Link.objects.all()

    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                name=form.cleaned_data['name'],
                comment=form.cleaned_data['comment'],
                post=post,
            )
            comment.save()
    context = {
        'blog': post,
        'social_links': social_links,
        'comments': comments,
        'form': form
    }
    return render(request, 'blog/detail.html', context)

home/views.py
from django.shortcuts import render
from home.models import Link
from projects.models import Project


def page(request):
    social_links = Link.objects.all()
    projects = Project.objects.all()
    context = {'projects': projects, 'social_links': social_links}
    return render(request, 'home/home.html', context)

projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
from projects.models import Project
from home.models import Link


def get_num_projects_with_related_tech(project):
    projects_tech_wise = {}
    for tech in project.get_all_tech:
        projects_tech_wise[tech.name] = Project.objects.filter(
            tech=tech).count() - 1
    return projects_tech_wise


def detail(request, slug):
    social_links = Link.objects.all()
    project_query_set = Project.objects.filter(slug=slug)
    if project_query_set.exists():
        project = project_query_set.first()
    else:
        return HttpResponse(status=404)

    context = {
        'project': project,
        'social_links': social_links,
    }
    
    previous_project_qs = Project.objects.filter(pk=project.pk - 1)
    if previous_project_qs.exists():
        previous_project = previous_project_qs.first()
        context['previous'] = previous_project

    next_project_qs = Project.objects.filter(pk=project.pk + 1)
    if next_project_qs.exists():
        next_project = next_project_qs.first()
        context['next'] = next_project

    return render(request, 'projects/detail.html', context)

blog/templates/blog/base.html
{% extends 'home/base.html' %}

{% block header_content %}
    <!-- ==================== BANNER ====================== -->
    <section data-position-y=top>
        <div style="height: 7em; position: relative;">
        </div>
    </section>
{% endblock %}


{% block content %}
    <!-- ==================== BLOG ====================== -->
    <section id='services' class="s-services light-gray">

        <div class="row section-header details mid" data-aos="fade-up">
            <div class="col-full">
                <h1 class="display-1">Blog</h1>
                <h3 class="subhead">Thoughts on SLAM, deep learning, robotics, entrepreneurship, self-development, and more.</h3>
            </div>
        </div>

        <div class="row services-list block-1-4 block-m-1-2 block-tab-full details mid">
            {% for blog in blog_posts %}
            <div class="col-block service-item " data-aos="fade-up">
                <div class="service-icon service-icon--brand-identity">
                    <a href="{% url 'blog:article' blog.slug %}"><img src="{{ blog.image.url }}" alt="{{ blog.slug }}"></a>
                </div>
                <div class="service-text">
                    <h3 class="h4">{{ blog.title }}</h3>
                    <p>{{ blog.date }}</p>
                </div>
            </div>
            {% endfor %}
        </div>

        {% if blog_posts.has_other_pages %}
            <nav data-pagination>
                <ul>
                    {% if blog_posts.has_previous %}
                        <li><a href="?page={{ blog_posts.previous_page_number }}"><i class="fa fa-chevron-left"></i></a></li>
                    {% endif %}

                    {% for i in blog_posts.paginator.page_range %}
                        {% if blog_posts.number == i %}
                            <li><a href="?page={{ i }}" class="active">{{ i }}</a></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    
                    {% if blog_posts.has_next %}
                        <li><a href="?page={{ blog_posts.next_page_number }}"><i class="fa fa-chevron-right"></i></a></li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </section>
{% endblock %}


{% block footer_content %}
    <!-- ==================== SOCIAL FOOTER ====================== -->
    <section id="contact" class="s-contact">
        <div class="col-full cl-copyright" style="margin-bottom: 1rem; margin-top: 1rem;">
            <script>document.write(new Date().getFullYear());</script> | <a href="/">Sahib Dhanjal</a>
            <ul class="contact-social">
                {% for social in social_links %}
                    {% if social.show %}
                        <li><a href="{{ social.link }}" target="_blank"><i class="{{ social.img_class }}"></i></a></li>        
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'home/base.html' %}

{% block header_content %}
    <!-- ==================== BANNER ====================== -->
    <section data-position-y=top>
        <div style="height: 7em; position: relative;">
        </div>
    </section>
{% endblock %}


{% block content %}
    <!-- ==================== BLOGS ====================== -->
    <section class="light-gray" style="width: 100%">

        <!-- div containing the blog material -->
        <div class="row tab-full mid details">
            <h1 class="display-1 display-1--dark">{{ blog.title }}</h1>
            <h3 class="subhead subhead--dark">{{ blog.subtitle }}</h3>
            <img src="{{ blog.image.url }}" alt="{{ blog.slug }}">
			<p class="drop-cap" style="text-align: justify; line-height: 1.42">{{ blog.description|safe }}</p>
            
            <h4 style="font-family: domine-bold;">// Categories</h4>
            <p>
                {% for category in blog.get_all_categories %} 
                    <code>{{ category }}</code>
                {% endfor %}
            </p>

            <!-- div containing the comments for the blog -->
            <div>
                <form action="/blog/{{ blog.slug }}/" method="post">
                    {% csrf_token %}
                    <label for="sampleInput">Your Name</label>
                    {{ form.name }}
                    <label for="sampleInput">Comment</label>
                    {{ form.comment }}
                    <button type="submit" class="btn btn--stroke">Submit</button>
                </form>
                
                {% for comment in comments %}

                    <blockquote cite="http://where-i-got-my-info-from.com">
                        <p>{{ comment.comment }}</p>
                        <cite>
                            <a>{{ comment.name }} | {{ comment.date }}</a>
                        </cite>
                    </blockquote>
                    <hr>
                {% endfor %}

            </div>
        </div>

    </section>

{% endblock %}


{% block footer_content %}
    <!-- ==================== SOCIAL FOOTER ====================== -->
    <section id="contact" class="s-contact">
        <div class="col-full cl-copyright" style="margin-bottom: 1rem; margin-top: 1rem;">
            <script>document.write(new Date().getFullYear());</script> | <a href="/">Sahib Dhanjal</a>
            <ul class="contact-social">
                {% for social in social_links %}
                    {% if social.show %}
                        <li><a href="{{ social.link }}" target="_blank"><i class="{{ social.img_class }}"></i></a></li>        
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

home/templates/home/about.html
{% extends 'home/base.html' %}

{% block header_content %}
    <!-- ==================== BANNER ====================== -->
    <section data-position-y=top>
        <div style="height: 7em; position: relative;">
        </div>
    </section>
{% endblock %}

{% block content %}

{% endblock %}

{% block footer_content %}
    <!-- ==================== SOCIAL FOOTER ====================== -->
    <section id="contact" class="s-contact">
        <div class="col-full cl-copyright" style="margin-bottom: 1rem; margin-top: 1rem;">
            <script>document.write(new Date().getFullYear());</script> | <a href="/">Sahib Dhanjal</a>
            <ul class="contact-social">
                {% for social in social_links %}
                    {% if social.show %}
                        <li><a href="{{ social.link }}" target="_blank"><i class="{{ social.img_class }}"></i></a></li>        
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113408615-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-113408615-1');
    </script>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
	<title>Sahib Dhanjal</title>
    <meta name="author" content="Sahib Singh Dhanjal">
    <meta name="description" content=" Sahib Singh Dhanjal Portfolio website">
    <meta name="keywords" content="portfolio, star wars, star, wars, robot, robotics, roboticist, University, of, michigan, university of michigan, ann arbor, flint, dearborn, bits, pilani, birla institute of technology and science, birla, institute, technology, science, pilani, hyderabad, goa, personal, projects, robot Kinematic, kinematics, path planner, path, planning, turtlebot, masters, football, soccer, Programmer, coder, coding, programming, machine learning, deep learning, tensor flow, computer vision, C/C++, JavaScript, java, python,Formula, student, fsae, italy, robotx, maritime, autonmous, slam, localization, mapping, vehicle, dynamics, inspired, Karters, fs">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendor.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts.css' %}">

    <!-- script
    ================================================== -->
    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

</head>
<body id="top">
    <!-- =================== HEADER ======================= -->
    <header class="s-header">
        <div class="header-logo">
            <a class="site-logo" href="/">
                <h1 style="font-family: sans-serif; font-size: 3rem; color: white; font-family: domine-bold, sans-serif;">
                    Sahib Dhanjal
                </h1>
            </a>
        </div>
        <div class="nav-mobile">
            <a id="nav-toggle" href="#!"><span></span></a>
        </div>
        <nav class="header-nav">
            <ul class="header-nav__list">
                <li><a href="/">Work</a></li>
                <li><a href="/blog">Blog</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="https://docs.google.com/document/d/1t2QLEwItGmX8AOK7teRTdotwSPwrbQxdyiDk8b1ZrA4/" target="blank">Resume</a></li>
            </ul>
        </nav>
    </header>

	{% block header_content %}
	{% endblock header_content %}

    {% block content %}
    {% endblock content %}

    {% block footer_content %}
    {% endblock footer_content %}

    <!-- photoswipe background
    ================================================== -->
    <div aria-hidden="true" class="pswp" role="dialog" tabindex="-1">

        <div class="pswp__bg"></div>
        <div class="pswp__scroll-wrap">

            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>

            <div class="pswp__ui pswp__ui--hidden">
                <div class="pswp__top-bar">
                    <div class="pswp__counter"></div><button class="pswp__button pswp__button--close" title="Close (Esc)"></button><button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button> <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                            <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div>
                </div><button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button> <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>
            </div>

        </div>
    </div>
    <!-- end photoSwipe background -->

    <!-- Java Script
    ================================================== -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

home/templates/home/home.html
{% extends 'home/base.html' %}

{% block header_content %}
    <!-- ==================== BANNER ====================== -->
    <section id="home" class="s-home target-section" data-parallax="scroll" data-position-y=top>
        <div class="fancy-text" style="height: 35em; position: relative;">
            <svg class="fancy-text__main center">
                <symbol id="s-text">
                    <text text-anchor="middle" x="50%" y="80%">Hello World</text>
                </symbol>
                <g class = "g-ants">
                    <use xlink:href="#s-text" class="text-copy"></use>
                    <use xlink:href="#s-text" class="text-copy"></use>
                    <use xlink:href="#s-text" class="text-copy"></use>
                    <use xlink:href="#s-text" class="text-copy"></use>
                    <use xlink:href="#s-text" class="text-copy"></use>
                </g>
            </svg>
        </div>
    </section>
{% endblock %}

{% block content %}
    <!-- ==================== PROJECTS ====================== -->
    <section id='works' class="s-works">
        <div class="row masonry-wrap">
            <div class="masonry">
                {% for project in projects%}
                    {% if project.show %}
                        <div class="masonry__brick" data-aos="fade-up">
                            <div class="item-folio">
                                <div class="item-folio__thumb">
                                    <a href="{% url 'projects:detail' project.slug %}" class="thumb-link" title="{{ project.title }}">
                                        <img src="{{ project.image.url }}" alt="{{ project.slug }}">
                                    </a>
                                </div>

                                <div class="item-folio__text">
                                    <h3 class="item-folio__title">{{ project.title }}</h3>
                                    <p class="item-folio__cat">
                                        {{ project.subtitle }}
                                    </p>
                                </div>

                                <a class="item-folio__project-link" title="View Brief" target="_blank">View Brief</a>

                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

{% block footer_content %}
    <!-- ==================== SOCIAL FOOTER ====================== -->
    <section id="contact" class="s-contact">
        <div class="col-full cl-copyright" style="margin-bottom: 1rem; margin-top: 1rem;">
            <script>document.write(new Date().getFullYear());</script> | <a href="/">Sahib Dhanjal</a>
            <ul class="contact-social">
                {% for social in social_links %}
                    {% if social.show %}
                        <li><a href="{{ social.link }}" target="_blank"><i class="{{ social.img_class }}"></i></a></li>        
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

projects/templates/projects/detail.html
{% extends 'home/base.html' %}

{% block header_content %}
    <!-- ==================== BANNER ====================== -->
    <section data-position-y=top>
        <div style="height: 7em; position: relative;">
        </div>
    </section>
{% endblock %}


{% block content %}
    <!-- ==================== PROJECTS ====================== -->
    <section class="light-gray" style="width: 100%">

        <div class="row tab-full mid details">
            <h1 class="display-1 display-1--dark">{{ project.title }}</h1>
            <h3 class="subhead subhead--dark">{{ project.subtitle }}</h3>
            <img src="{{ project.image.url }}" alt="{{ project.slug }}">
            <p class="drop-cap">{{ project.description|safe }}</p>
            <h4 style="font-family: domine-bold;">// TechStack  </h4>
            <p>
                {% for tech in project.get_all_tech %} 
                    <code>{{ tech }}</code>
                {% endfor %}
            </p>
            <hr>
            <!-- {% url 'projects:detail' project.slug %} -->
            <div style="height: 50px">
                <a href="#" style="float: left;"><i class="fa fa-chevron-left"></i> {{ previous.title }} </a>

                <a href="#" style="float: right;"> {{ next.title }} <i class="fa fa-chevron-right"></i></a>
            </div>
        </div>

    </section>
{% endblock %}


{% block footer_content %}
    <!-- ==================== SOCIAL FOOTER ====================== -->
    <section id="contact" class="s-contact">
        <div class="col-full cl-copyright" style="margin-bottom: 1rem; margin-top: 1rem;">
            <script>document.write(new Date().getFullYear());</script> | <a href="/">Sahib Dhanjal</a>
            <ul class="contact-social">
                {% for social in social_links %}
                    {% if social.show %}
                        <li><a href="{{ social.link }}" target="_blank"><i class="{{ social.img_class }}"></i></a></li>        
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}